### ISSUE TITLE
It's almost impossible to add multiple organizations in admin

### ISSUE THREAD

**Issue by peltonc** [AASHE/hub#229] opened 2016-02-29 21:57 UTC
Trying to add an organization to a resource that already has two associated with it
http://hub.aashe.org/admin/content/tool/8716/

**Comment by monika-aashe** [comment] 2016-02-29 22:05
I don't see what the issue is. In admin, you just need to hit command/control to add multiple orgs. I didn't try saving so as not to mess up a valid resource so maybe it doesn't let you save or something?

**Comment by juliandsmith** [comment] 2016-02-29 22:12
I've had this challenge too. I think the issue is that the list isn't perfectly alphabetical so it can be really hard to find the organization you are looking for. I almost gave up this morning. You can't just start typing and have it autofill as on the front end. 

Eventually, it would be nice if the back end editing system could just look/function the same as the front end submission system.

**Comment by monika-aashe** [comment] 2016-02-29 22:17
That makes sense, thanks. If Ben says we can't make admin function like the front-end, would ensuring the list is alphabetical help resolve the issue?

**Comment by peltonc** [comment] 2016-02-29 22:20
That would help, I think.

On Mon, Feb 29, 2016 at 10:17 PM, monika-aashe <notifications@github.com>
wrote:

> That makes sense, thanks. If Ben says we can't make admin function like
> the front-end, would ensuring the list is alphabetical help resolve the
> issue?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/AASHE/hub/issues/229#issuecomment-190423503>.
>

-- 
Join us in Baltimore, Maryland from Oct. 9 - 12 for the AASHE 2016 
Conference & Expo, themed Beyond the Campus. 


Connect with us:   Website <http://www.aashe.org/> | Facebook 
<https://www.facebook.com/aasheorg> | Twitter 
<https://twitter.com/AASHENews> | LinkedIn 
<http://www.linkedin.com/company/aashe>

------------------------------
Email Confidentiality Notice 
<http://www.aashe.org/email_confidentiality_notice>

**Comment by jamstooks** [comment] 2016-03-15 02:53
This is a dupe of #56. I'll raise the priority of that one.

**Closed by jamstooks** 2016-03-15 02:53 UTC
Labels: admin, prio:high

**Comment by monika-aashe** [comment] 2016-03-17 02:04
Looks like it's working perfectly! The 2-word issue is resolved in admin and in submission forms, and the tags filter is awesome! I can't wait to start linking to this feature when someone says "I'm looking for resources about..."

I do have a minor request - it can definitely wait until post-launch, but is there a way to update the tag output so instead of saying "search results" it says "tag results for ..." or something along those lines? I'll submit a ticket for 1d.
