### ISSUE TITLE
Clarifying Date Field Labels

### ISSUE THREAD

**Issue by juliandsmith** [AASHE/hub#333] opened 2016-05-31 18:40 UTC
Right now, we have two different and unrelated date fields associated with each resource in the Hub that include the word "Created" in them. One is an automatic time stamp indicating when the the resource was created in the Hub (i.e., the date/time when someone hit the "Submit Resource" button"). The other "created, published, or presented" is a user-entered field that refers to when the resource itself was created, published, or presented. 

Similarly, we have have two different date fields that use the word published. The first is a time stamp value that indicates when the resource page was made visible via the Hub (i.e., the date/time that someone approved a resource for posting via the administrative view). The second is the "created, published, or presented" field described above.

To avoid confusion and more clearly distinguish between the different date fields, we should relabel the date fields at "Submitted" (for when a user clicked submit), "Posted" (for when we approve a resource to be shared through the Hub), and "Created, Published, or Presented" (for when the the resource was created, published, or presented (which is unrelated to it's appearance the Hub). 

These changes to the terminology should be made consistently throughout the Hub, including the various Admin views.

**Comment by monika-aashe** [comment] 2016-05-31 18:46
This is a dupe of #224 - we can probably close/update either.

**Comment by juliandsmith** [comment] 2016-05-31 18:50
Whoops. I didn't remember that you'd added those items to the other ticket. This one seems a little broader (in that it refers to all instances where we use these terms rather than the specific cases described in #224) so I think we should close 224 and just incorporate it here by reference.

**Comment by monika-aashe** [comment] 2016-05-31 19:00
I'm fine with that but I do like to see the changes in list view: 
- Date Submitted - the date that a resource was submitted to the Hub (currently "Created")
- Date Posted - the date a resource was approved in the Hub (currently "Published")
- Date Created, Published or Presented - the date the came to be (it looks like this has already been updated)

**Comment by juliandsmith** [comment] 2016-07-13 15:17
As shown below, search results still use "Published" to refer to the date the resource was made available through the Hub. Can we change this to "Posted" for consistency with the above.
![image](https://cloud.githubusercontent.com/assets/15839046/16808659/5e9cfe08-48eb-11e6-9a2d-8635e0c94ab4.png)

**Comment by monika-aashe** [comment] 2016-07-13 16:36
Also in the Sort section of the filters, is it possible to update "Most Recent" to "Recently Posted"?

![screen shot 2016-07-13 at 12 36 06 pm](https://cloud.githubusercontent.com/assets/15214797/16811448/6885a496-48f6-11e6-9afb-7aa45de0b848.png)

**Comment by monika-aashe** [comment] 2016-07-13 16:51
@baronvonvaderham - for consistency, the "Created, Published, Presented" option should also have "Recently" at the beginning.

**Comment by baronvonvaderham** [comment] 2016-07-13 16:53
Ok, good timing, I can add this in before I deploy to production

**Comment by juliandsmith** [comment] 2016-07-13 16:54
Since it's a sort option, shouldn't the options just by "Date posted" and Date created, published, presented". You aren't really sorting by "recently posted", you are just sorting by date.

**Comment by baronvonvaderham** [comment] 2016-07-13 16:56
I think it makes sense either way. Since it's a sort, choosing a field name is logical, the recently is redundant but still clear what's happening. I don't have a strong preference.

**Comment by monika-aashe** [comment] 2016-07-13 17:08
I agree with Scott about consistency and "recently" being somewhat more clear. Julian, you can be the final decider on which way we go

**Comment by baronvonvaderham** [comment] 2016-07-13 17:11
Proposal: Don't use "Recently" in the fields, but rename "Sort" as "Sort by..." to be more clear.

**Comment by baronvonvaderham** [comment] 2016-07-13 17:30
It's now up on the dev site like this if you want to see how that would look.

**Comment by monika-aashe** [comment] 2016-07-13 17:46
Looks good to me, though I would prefer "Sort by:" instead of "Sort by..." 
I like it!

**Comment by juliandsmith** [comment] 2016-07-13 17:51
Yep, that seems right to me. I prefer "Sort by:" too

**Comment by baronvonvaderham** [comment] 2016-07-13 19:34
Deployed, just need to wait on cache to expire.

**Closed by baronvonvaderham** 2016-07-13 19:34 UTC
Labels: filter/tag, Fixed-in-source, prio:med, submission form, UI
