### ISSUE TITLE
Fix URL for uploaded files

### ISSUE THREAD

**Issue by juliandsmith** [AASHE/hub#461] opened 2017-06-06 17:16 UTC
The URL for uploaded files seem to have reverted back to the ugly https://s3-us-west-2.amazonaws.com/.... urls (https://s3-us-west-2.amazonaws.com/aashe-hub-production/uploads/eco-reps_guide.pdf). We had previously fixed this so that the URLS were in the http://hub-media.aashe.org/uploads/... format (e.g., http://hub-media.aashe.org/uploads/PCSD_Essex_Report.pdf) 

It looks more professional to have these files appear to be on our own server rather than Amazon AWS and I don't really like advertising Amazon so I'd like to switch it back to hub-media.aashe.org domain.

**Comment by monika-aashe** [comment] 2017-06-21 20:32
Ask LL if there is a way to go back to hub-media.aashe.org for uploads (or similar), and also adjust retroactively.

**Comment by unbracketed** [comment] 2017-12-18 20:42
I'm done with this ticket for now.  I did not find any current places in the code where a non-desirable URL would be set so will assume these entries came from old code configurations and/or prior import processes. 

For the existing data, there was a mix of URLs with some on AWS URLs, some on http vs. https.  I wrote a few cleanup scripts to normalize the URLs for each of:

* the source image
* the medium thumbnail
* the small thumbnail

All the image URLs site-wide should now be originating from `https://hub-media.aashe.org/`

---

I made a DB backup prior to applying my fixes: `b540`

**Comment by monika-aashe** [comment] 2017-12-19 16:59
Hey, @unbracketed - it looks like this fix may have resulted in a bunch of bad links. Yesterday when I was working on fixing bad URLs in the [Hub Link check](https://hub.aashe.org/_ad/linkcheck/), there were about 390. However today, there are over 1,000. If you glance through the link check, there are a bunch of new image links that are bad, and I don't think that was the case before. Is this something that you can prioritize or back out of until we can do a full fix?

**Comment by unbracketed** [comment] 2017-12-19 17:05
@monika-aashe  Yes I will look into it this morning, in about 90 minutes.  I can rollback the images data without much hassle if needed - ideally I'll be able to resolve any problems quickly.

**Comment by monika-aashe** [comment] 2017-12-19 17:06
Great, thank you!

**Comment by unbracketed** [comment] 2017-12-19 17:20
I took a quick look and see what the problem is.  URLs that I changed from

`https://aashe-hub-production.s3.amazonaws.com` need to be stripped of the S3 bucket name in their path:

`/aashe-hub-production/uploads/some-image.jpg`  needs to be
`/uploads/some-image.jpg`

I did spot check a few URLs during testing to make sure the new URLs would resolve, but must not have tested any that came from this particular root URL.  This will be resolved this morning.

**Comment by unbracketed** [comment] 2017-12-19 19:33
Update: The data should be fixed for the broken images and those should be appearing on the site.  

I'm working on clearing out the linkcheck errors but ran into another problem related to the change in the size of the Website URL field we made a few months ago.  Linkcheck stores its own copy of the URL and a few of the image URLs are now longer than what linkcheck's table expects. I'll patch that up and probably open a separate ticket to track that.

**Comment by juliandsmith** [comment] 2018-02-27 21:57
I just noticed that this problem is occurring again. [This resource](https://hub.aashe.org/browse/publication/18786/Beacons-Not-Towers-How-Higher-Education-Can-Help-Achieve-the-Sustainable-Development-Goals) was posted last week and, if you look at the URL for the doc upload, you'll see it is in the ugly https://s3-us-west-2.amazonaws.com/.... format again. 

This is second time the fix has come undone so it'd be helpful to understand why this is happening.

**Comment by dodget** [comment] 2018-03-26 20:10
I don't have much insight as to why this is happening to only some, but I can modify the string of the url so that 'https://s3-us-west-2.amazonaws.com/aashe-hub-production/' is always replaced with 'https://hub-media.aashe.org/'

I have this working locally, and I can roll it into the next deploy after some testing.

**Comment by dodget** [comment] 2018-03-28 19:46
The change has been deployed, and it looks good. Please, let me know if you see any other issues!

**Comment by dodget** [comment] 2018-03-30 19:10
Closing, for now.

**Closed by dodget** 2018-03-30 19:10 UTC
Labels: contractor, prio:med

**Comment by monika-aashe** [comment] 2018-04-06 21:27
Not an issue but more an FYI: I'm seeing the Amazon link in the upload field on the Admin side, but it appears to convert to the more favorable link on the public side. Magic!

https://hub.aashe.org/_ad/content/publication/18920/change/
https://hub.aashe.org/browse/publication/18920/Innovative-Solutions-for-Reducing-Waste-at-Skidmore-College-Analyzing-the-Carbon-Footprint-Economics-of-Paper-Towels-vs-Electric-Hand-Dryers
