### ISSUE TITLE
Create toolkit style pages for each content type

### ISSUE THREAD

**Issue by juliandsmith** [AASHE/hub#295] opened 2016-04-20 04:05 UTC
Currently, clicking any of the content type boxes takes the user directly a list of search results. This means we don't have a place to properly market the resources in that content type. For example, for SEO purposes and demonstrating member value, it would be helpful to be able to promote our academic programs list as being one of the most comprehensive lists of academic programs related to sustainability. 

To enable this, create a landing page for each content type that includes an editable text box, multiview ad, list of new resources in that content type, and some kind of interactive visual representation of the resources in that content type. This could be a simple word cloud based on tags in that content type or a chart. In the Academic Programs content type for example, the visual could be   a clickable bar chart showing the total number of academic programs in each discipline.

**Comment by monika-aashe** [comment] 2016-04-20 13:03
I wonder if for the time-being, we can add an editable text section at the top of the Resources sections of the content type views?

**Comment by monika-aashe** [comment] 2016-07-12 19:25
Here is an draft mock-up for the Content Type landing pages:
https://docs.google.com/presentation/d/1pWWBB9aqei87ARj2O1C5k25aHAqotxkul31XJoxlAVk/edit#slide=id.g115be3eb5d_0_137

**Comment by monika-aashe** [comment] 2016-08-24 16:57
@juliandsmith - 
I reviewed the Content Type landing pages more closely and my recommendations are below - for the most part, they follow the suggestion to display either Discipline OR topic based on whether Discipline is required, with a few caveats:

- Academic Programs - show Discipline only
- Case Studies - show Topic only **(okay with also showing Discipline)**
- Conference Presentations - show Topic only
- Course Materials - show Discipine only
- Outreach Materials - show Topic only **(though most will relate to Campus Engagement, so maybe no graph at all?)**
- Photographs - show Topic only
- Publications - show Topic only **(okay with also showing Discipline)**
- Research Centers - show Discipline only
- Tools - show Topic only
- Videos & Webinars - show Topic only

What are your thoughts on displaying both Discipline and Topic for Case Studies and Publications? What about the fact that most Outreach Materials are listed as Campus Engagement and not doing a chart at all?

**Comment by juliandsmith** [comment] 2016-08-24 17:19
I agree that both discipline and topic make sense for publications and case studies. 

Since many outreach materials do relate to a specific topic (even though we don't have many submitted at this point), I would keep the topic chart.

**Comment by monika-aashe** [comment] 2016-08-24 17:34
@baronvonvaderham - here is the final decision regarding whether to show graphs for Discipline, Topic, or both:

- Academic Programs - show Discipline only
- Case Studies - show Topic AND Discipline
- Conference Presentations - show Topic only
- Course Materials - show Discipine only
- Outreach Materials - show Topic only 
- Photographs - show Topic only
- Publications - show Topic AND Discipline
- Research Centers - show Discipline only
- Tools - show Topic only
- Videos & Webinars - show Topic only

**Comment by baronvonvaderham** [comment] 2016-08-24 17:36
Acknowledged. Just finished fixing the map data. Once I confirm this is all working I'll make the switch in the templates to make that happen.

**Comment by monika-aashe** [comment] 2016-08-24 17:44
8/24/16 decisions:

Dev version looks great so far! In addition to graph changes above, would be nice to incorporate the following:
- Links to the Topic/Discipline names and/or bars (For example, on the [Academic Programs page](http://aashe-hub-scott.herokuapp.com/browse/types/academicprogram/), clicking on "Business, Management & Finance" in the graph would take you to [this output](https://hub.aashe.org/browse/types/academicprogram/?search=&content_type=academicprogram&discipline=3&country=)

Map Features
Although we didn't discuss on the call, would it be possible to add the Resource Title to the map pin when clicked, along with Institution name, and then also a link to that resource? 

Also, what will we do when a single institution has multiple initiatives for a Content Type (e.g. University of California, Berkeley has [29 Academic Programs](https://hub.aashe.org/browse/?search=&content_type=academicprogram&organizations=18890&country=))

**Comment by baronvonvaderham** [comment] 2016-08-24 18:00
I'm working on that for the graphs. It's pretty tricky, though, as I can't just pass raw html strings into the javascript that generates it. There is a solution, it's just more complex than anticipated, requiring the construction of listener functions in the javascript to detect the clicks and process them. Not too bad, though.

I had briefly mentioned my plan for the map on the call: I don't want to overload those markers with data, and they're tricky to work with. I was going to simply change the name that's shown currently to a link to a search with the parameters content type=the page you're on, and organizations=that org.

That solves the problem of each organization having potentially dozens of resources in this content type, but still wanting to provide some functionality to get that list of resources easily. Maybe I can add a display of how many pieces of content that institution has under the name in there.

**Comment by monika-aashe** [comment] 2016-08-24 18:07
Okay, that makes sense - keep us posted if the fix for adding links in the graphs becomes too much - in could be a new feature later too. 

I like your solution for the maps too (sorry I missed that) - I'm assuming the link to the content type for that institution can be hyperlinked instead of displaying the actual URL? If so, the display name could say "University of California, Berkeley - 29 Academic Programs" or "University of California, Berkeley Academic Programs" if you can't do the counts.

**Comment by baronvonvaderham** [comment] 2016-08-25 17:57
Map is updated on dev now. Moving on to the graphs....

**Comment by monika-aashe** [comment] 2016-08-25 18:10
I like it! My only recommendation with the map is to update the text upon clicking on a pin to include "(s)" instead of "s" - So it says "1 Academic Program(s)" instead of "1 Academic Programs"

**Comment by baronvonvaderham** [comment] 2016-08-25 23:12
Everything is up, the graphs are now clickable.

I can't get those links in the map to read like that. This uses a predefined property (content_type_label) to generate those. It would take a not insignificant effort to modify at this point, so I left it for now unless someone feels REALLY strongly otherwise.

**Comment by monika-aashe** [comment] 2016-08-26 13:16
Are you sure it deployed? I'm not getting clickable graphs on the dev site or the real one...

**Comment by baronvonvaderham** [comment] 2016-08-26 15:59
Yeah unfortunately that's all it's able to make clickable. I was thinking something in the intro text would be sufficient, unless you wanted a text blurb above the graphs that's the same for every page.

**Comment by monika-aashe** [comment] 2016-08-26 16:13
Might make sense to do (editable) text blurb for the graphs to include this and a disclaimer:

Bars in graphs can be clicked to view resources that align to a particular category. Graph data may include higher total counts than what is indicated in total resources since a single resource may be listed under multiple topics and disciplines."

**Comment by baronvonvaderham** [comment] 2016-08-26 16:16
Ok, I can drop in a block_content and use the same key everywhere so they'll all be uniform. Do you want that above or below the graphs?

**Comment by monika-aashe** [comment] 2016-08-26 16:19
Above the charts directly below the tabs would be most prominent, so that's my vote.

**Comment by monika-aashe** [comment] 2016-08-26 16:22
Also, circling back to the map...
You mentioned that you can't get the map to read "1 Academic Program(s)", but is it possible to do a different variation like "Academic Programs: 1" While it seems minor, something that is grammatically correct would be better for a higher ed audience.

**Comment by baronvonvaderham** [comment] 2016-08-30 15:23
Ok, changes made, deploying to dev now. If you guys have no further changes I can merge this into production later today.

**Comment by baronvonvaderham** [comment] 2016-08-30 15:29
Oh and the login is still broken on dev. Looking into that. But the block content edit link would appear right above the graph. I wrapped it in a div so it has the same margins and such as the graphs themselves so it's nice and symmetric.

**Comment by jamstooks** [comment] 2016-08-30 22:12
Hey, @baronvonvaderham! I really like this and provided just a few technical comments on the pull request.

From a visual standpoint, I saw this "counter" option that the [Unify theme provides](http://htmlstream.com/preview/unify-v1.9.6/shortcode_compo_charts.html), that I thought might be really cool for the "At a Glance" section:

![screen shot 2016-08-30 at 4 09 23 pm](https://cloud.githubusercontent.com/assets/585436/18109010/58e5405e-6ecc-11e6-9385-a423dc561cb3.png)

Just a suggestion... it's really pretty though ;)

**Comment by baronvonvaderham** [comment] 2016-08-30 23:43
Seems like I should be able to add that in easily enough, just some different div classes. I'll tackle that in the morning.

**Comment by baronvonvaderham** [comment] 2016-08-31 17:37
Last update's up on dev: http://aashe-hub-scott.herokuapp.com/browse/types/academicprogram/

Assuming no objections, I'll be merging this and deploying into production tomorrow.

**Comment by monika-aashe** [comment] 2016-08-31 17:58
Awesome, love the map changes! I like the counters a lot too but have a few questions and suggested changes:
- Can you shrink the font a bit, since it's much bigger than the font on the rest of the site and looks a bit disjointed? 
- Once shrunken down, would it be possible to fit all 5 counters in a single row? (Currently staggered in two rows - see [example](http://aashe-hub-scott.herokuapp.com/browse/types/casestudy/)
- Some content types have 4 counters with Canadian Provinces missing (Academic Programs, Photographs, Publications, Research Centers, Tools). The rest have all five counters.

**Comment by baronvonvaderham** [comment] 2016-08-31 18:01
I'll try on the font. It's a plugin from Unify, but maybe I can override some CSS. If that works, then yeah, I can shrink it to one row.

Those missing provinces don't have any Canadian institutions represented. I have that display conditionally rather than saying "0 Canadian Provinces" and looking awkward.

**Comment by monika-aashe** [comment] 2016-08-31 18:09
Thanks for checking - that makes sense about the counters only having four instead of five - your solution is much better, but I hope that once this is deployed and all resources are included, each category will include five. 

I just noticed an issue where [Research Centers](http://aashe-hub-scott.herokuapp.com/browse/types/centerandinstitute/#charts-panel) don't display the summary chart - it should be the one displaying Academic Discipline.

Also, I noticed some discrepancies between the counters and map. For example, under [Tools](http://aashe-hub-scott.herokuapp.com/browse/types/tool/#map-panel), the counter says "4 Countries" but the map shows pins in two countries. Could this be because we don't have latitude/longitude data from certain resources in the ISS? If so, that's another field we may want to update during Salesforce clean-up.

**Comment by baronvonvaderham** [comment] 2016-08-31 18:12
Yes exactly. To create a marker it needs the lat/long from ISS. We ran an update on that back in.....November last year? When I was creating the SCPD and was adding maps to the profiles. I'm guessing some of the new members don't have that data.

I'll fix the Research Centers, probably just an oversight when I was creating those filter lists.

And I found a way to override that font size. I'll have all this packed up and deployed in a few minutes.

**Comment by juliandsmith** [comment] 2016-08-31 18:14
Is there any way the cursor could change to the pointing hand (as when hovering over other links) when you hover over the clickable areas of the bar chart? I would realize they were clickable otherwise.

**Comment by baronvonvaderham** [comment] 2016-08-31 18:16
Sadly no, that's a system governed thing in your browser. They aren't actually "clickable" in the traditional sense, there's nothing in the HTML document....instead you just select it, almost as if you were highlighting some text, when you click that region. There's a "listener" function that looks for those select events and triggers a redirect.

**Comment by baronvonvaderham** [comment] 2016-08-31 18:16
I believe Monika was planning on including some reminder text in the block_content above the graphs to clarify things.

**Comment by monika-aashe** [comment] 2016-08-31 18:17
Yes, about the reminder text, but we were hoping to have this appear below the graphs as a second block-content, separate from the Introduction block. 

Bars in graphs can be clicked to view resources that align to a particular category. Graph data may include higher total counts than what is indicated in total resources since a single resource may be listed under multiple topics and disciplines."

**Comment by baronvonvaderham** [comment] 2016-08-31 18:19
Ok, so you want the block to appear under the graphs? It's currently placed above the graphs, under the counters. I can swap it around if you want it somewhere else.

It will be editable like the intro block, but it's using a key shared across all content type pages, so you only have to do one.

**Comment by monika-aashe** [comment] 2016-08-31 18:21
Above or below doesn't matter to me, as long as its below the Summary Charts/Summary Map tabs. Has this not deployed to the dev site? I don't see it there yet.

**Comment by monika-aashe** [comment] 2016-08-31 18:23
One final question for now: Most Discipline Names (and the Coordination & Planning topic) have long titles, and they mostly get cut-off in the graphs. Would it be possible to make more room by moving the Y-axis to the left to allow for more room for labels? 

![screen shot 2016-08-31 at 2 19 33 pm](https://cloud.githubusercontent.com/assets/15214797/18141178/796876f6-6f86-11e6-8c4e-96cf984024c6.png)

**Comment by baronvonvaderham** [comment] 2016-08-31 18:32
The block is up on dev, but remember with admin broken on there you can't log in to see it. We'll double check on stage before we deploy. I'll be redeploying in a minute here with the revised counters, ran into a bug building JQuery on the server.

I actually played with that y-axis label a LOT when I first created them for exactly that reason. The problem is we really want those offsets equal for both graphs (for when both display) or else it looks really bad. This was the best compromise that displayed all of the Topic labels except I think one really long one, whereas almost every single discipline is gigantic and gets cut off unless I literally give it half of the entire block.

If you guys feel otherwise I can shift that easily enough, but that's just the reasoning behind choosing that size.

**Comment by monika-aashe** [comment] 2016-08-31 18:42
Gotcha thanks. On the y-axis, if it's not a lot more work at this stage, I'd be in favor of moving it slightly more to the right for both graphs so that Coordination & Planning (the only one that doesn't display on the Topics graph) is fully visible. Most of the Content Types only display the Topics graph anyway. Maybe a few more of the Academic Disciplines will show up too as a result, but I think it's fine if some are cut off.

**Comment by baronvonvaderham** [comment] 2016-08-31 18:44
Ok that works. I'll expand it slightly to fit that title then.

For Research Centers, I had to use the full label "Research Centers & Institutes"; I had just copied what was in the list you provided and didn't think to double check that.

**Comment by baronvonvaderham** [comment] 2016-08-31 18:50
Deployed. I think that should cover everything. It did reveal more of the Discipline labels.

http://aashe-hub-scott.herokuapp.com/browse/types/casestudy/

**Comment by monika-aashe** [comment] 2016-08-31 19:04
It looks like the font is larger on some Academic Discipline y-axis labels but not all. For those that only display Academic Disciplines (Academic Programs, Course Materials, Research Centers) see how Sustainability Studies & Science is cut off? Not so on the graphs that include both Disciplines and Topics.

Beyond that, everything looks great, I'm really excited to see this go live. Nice work! :)

**Comment by baronvonvaderham** [comment] 2016-08-31 19:26
Ah, yeah I see what you're talking about. That's because on some of those they have fewer disciplines, so you'll see the bars get a little bigger and space out a tiny bit more. I don't think there's anything I can do to override it, though.

**Comment by jamstooks** [comment] 2016-08-31 21:52
I just want to mention that I *really like* the larger font size for the numbers. I wouldn't shrink them too much... just if you need them to fit within the width of the row.

We're using the Unify theme for a reason... because we like the design elements there.

**Comment by baronvonvaderham** [comment] 2016-09-01 00:51
A version without the size modification is up on dev. I agree, looks fine with the larger numbers.

**Comment by monika-aashe** [comment] 2016-09-02 17:46
Hey @jamstooks and @baronvonvaderham - the content type landing pages on the live site look great, but there's an internal server error on the Publications page that means that section is not accessible. Can this be fixed before the weekend?

**Comment by juliandsmith** [comment] 2016-09-02 20:03
Since all of the new resources on any given content type's landing page are going to be associated with that content type, including the content type within the new resources sidebar is redundant. Can we replace the content type with the organization name(s), which seems more relevant in this context?

![image](https://cloud.githubusercontent.com/assets/15839046/18216727/a8d06a88-7126-11e6-8175-61739b39fc79.png)

**Closed** 2016-09-12 19:15 UTC
Labels: display, prio:high
